/*
 * Payfactory Api
 * Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BankDetailsModel;
import com.konfigthis.client.model.BusinessDetailsModel;
import com.konfigthis.client.model.CustomerServiceContactModel;
import com.konfigthis.client.model.OwnerModel;
import com.konfigthis.client.model.PersonModel;
import com.konfigthis.client.model.PricingModel;
import com.konfigthis.client.model.ProcessingDetailsModel;
import com.konfigthis.client.model.RiskContactModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ApplicationSubmitRequestModel
 */
public class ApplicationSubmitRequestModelTest {
    private final ApplicationSubmitRequestModel model = new ApplicationSubmitRequestModel();

    /**
     * Model tests for ApplicationSubmitRequestModel
     */
    @Test
    public void testApplicationSubmitRequestModel() {
        // TODO: test ApplicationSubmitRequestModel
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    public void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'isvName'
     */
    @Test
    public void isvNameTest() {
        // TODO: test isvName
    }

    /**
     * Test the property 'businessDetails'
     */
    @Test
    public void businessDetailsTest() {
        // TODO: test businessDetails
    }

    /**
     * Test the property 'customerServiceContact'
     */
    @Test
    public void customerServiceContactTest() {
        // TODO: test customerServiceContact
    }

    /**
     * Test the property 'riskContact'
     */
    @Test
    public void riskContactTest() {
        // TODO: test riskContact
    }

    /**
     * Test the property 'businessContact'
     */
    @Test
    public void businessContactTest() {
        // TODO: test businessContact
    }

    /**
     * Test the property 'processingDetails'
     */
    @Test
    public void processingDetailsTest() {
        // TODO: test processingDetails
    }

    /**
     * Test the property 'bankDetails'
     */
    @Test
    public void bankDetailsTest() {
        // TODO: test bankDetails
    }

    /**
     * Test the property 'pricingStructure'
     */
    @Test
    public void pricingStructureTest() {
        // TODO: test pricingStructure
    }

    /**
     * Test the property 'owners'
     */
    @Test
    public void ownersTest() {
        // TODO: test owners
    }

}
