/*
 * Payfactory Api
 * Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CreateSessionRequestSignerModel;
import com.konfigthis.client.model.SessionBusinessDetailsModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateSessionRequest
 */
public class CreateSessionRequestTest {
    private final CreateSessionRequest model = new CreateSessionRequest();

    /**
     * Model tests for CreateSessionRequest
     */
    @Test
    public void testCreateSessionRequest() {
        // TODO: test CreateSessionRequest
    }

    /**
     * Test the property 'pricingPlanId'
     */
    @Test
    public void pricingPlanIdTest() {
        // TODO: test pricingPlanId
    }

    /**
     * Test the property 'signer'
     */
    @Test
    public void signerTest() {
        // TODO: test signer
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'redirectUrl'
     */
    @Test
    public void redirectUrlTest() {
        // TODO: test redirectUrl
    }

    /**
     * Test the property 'completeUrl'
     */
    @Test
    public void completeUrlTest() {
        // TODO: test completeUrl
    }

    /**
     * Test the property 'refreshUrl'
     */
    @Test
    public void refreshUrlTest() {
        // TODO: test refreshUrl
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    public void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'businessDetails'
     */
    @Test
    public void businessDetailsTest() {
        // TODO: test businessDetails
    }

}
