/*
 * Payfactory Api
 * Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PricingModelBillingFrequencyEnum;
import com.konfigthis.client.model.PricingModelPricingStructureCardModel;
import com.konfigthis.client.model.PricingProgramEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PricingModel
 */
public class PricingModelTest {
    private final PricingModel model = new PricingModel();

    /**
     * Model tests for PricingModel
     */
    @Test
    public void testPricingModel() {
        // TODO: test PricingModel
    }

    /**
     * Test the property 'amex'
     */
    @Test
    public void amexTest() {
        // TODO: test amex
    }

    /**
     * Test the property 'visaMasterCard'
     */
    @Test
    public void visaMasterCardTest() {
        // TODO: test visaMasterCard
    }

    /**
     * Test the property 'discover'
     */
    @Test
    public void discoverTest() {
        // TODO: test discover
    }

    /**
     * Test the property 'monthlyFee'
     */
    @Test
    public void monthlyFeeTest() {
        // TODO: test monthlyFee
    }

    /**
     * Test the property 'billingFrequency'
     */
    @Test
    public void billingFrequencyTest() {
        // TODO: test billingFrequency
    }

    /**
     * Test the property 'program'
     */
    @Test
    public void programTest() {
        // TODO: test program
    }

}
