/*
 * Payfactory Api
 * Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProcessingDetailsModel
 */
public class ProcessingDetailsModelTest {
    private final ProcessingDetailsModel model = new ProcessingDetailsModel();

    /**
     * Model tests for ProcessingDetailsModel
     */
    @Test
    public void testProcessingDetailsModel() {
        // TODO: test ProcessingDetailsModel
    }

    /**
     * Test the property 'billingDescriptor'
     */
    @Test
    public void billingDescriptorTest() {
        // TODO: test billingDescriptor
    }

    /**
     * Test the property 'monthlyTransactionVolume'
     */
    @Test
    public void monthlyTransactionVolumeTest() {
        // TODO: test monthlyTransactionVolume
    }

    /**
     * Test the property 'lowTransactionAmount'
     */
    @Test
    public void lowTransactionAmountTest() {
        // TODO: test lowTransactionAmount
    }

    /**
     * Test the property 'averageTransactionAmount'
     */
    @Test
    public void averageTransactionAmountTest() {
        // TODO: test averageTransactionAmount
    }

    /**
     * Test the property 'highTransactionAmount'
     */
    @Test
    public void highTransactionAmountTest() {
        // TODO: test highTransactionAmount
    }

    /**
     * Test the property 'dailyTransactionCount'
     */
    @Test
    public void dailyTransactionCountTest() {
        // TODO: test dailyTransactionCount
    }

    /**
     * Test the property 'cardNotPresentPerctange'
     */
    @Test
    public void cardNotPresentPerctangeTest() {
        // TODO: test cardNotPresentPerctange
    }

    /**
     * Test the property 'cardPresentPerctange'
     */
    @Test
    public void cardPresentPerctangeTest() {
        // TODO: test cardPresentPerctange
    }

}
