/*
 * Payfactory Api
 * Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AddressModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * SessionBusinessDetailsModel
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SessionBusinessDetailsModel {
  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private AddressModel address;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  private String phone;

  public static final String SERIALIZED_NAME_ESTABLISHED_DATE = "establishedDate";
  @SerializedName(SERIALIZED_NAME_ESTABLISHED_DATE)
  private LocalDate establishedDate;

  public static final String SERIALIZED_NAME_LEGAL_NAME = "legalName";
  @SerializedName(SERIALIZED_NAME_LEGAL_NAME)
  private String legalName;

  public static final String SERIALIZED_NAME_DBA_NAME = "dbaName";
  @SerializedName(SERIALIZED_NAME_DBA_NAME)
  private String dbaName;

  public static final String SERIALIZED_NAME_TAX_ID = "taxId";
  @SerializedName(SERIALIZED_NAME_TAX_ID)
  private String taxId;

  public static final String SERIALIZED_NAME_WEBSITE = "website";
  @SerializedName(SERIALIZED_NAME_WEBSITE)
  private String website;

  public SessionBusinessDetailsModel() {
  }

  public SessionBusinessDetailsModel address(AddressModel address) {
    
    
    
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AddressModel getAddress() {
    return address;
  }


  public void setAddress(AddressModel address) {
    
    
    
    this.address = address;
  }


  public SessionBusinessDetailsModel phone(String phone) {
    
    
    
    
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5551234567", value = "")

  public String getPhone() {
    return phone;
  }


  public void setPhone(String phone) {
    
    
    
    this.phone = phone;
  }


  public SessionBusinessDetailsModel establishedDate(LocalDate establishedDate) {
    
    
    
    
    this.establishedDate = establishedDate;
    return this;
  }

   /**
   * Date your business was established
   * @return establishedDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Mon Feb 02 16:00:00 PST 1959", value = "Date your business was established")

  public LocalDate getEstablishedDate() {
    return establishedDate;
  }


  public void setEstablishedDate(LocalDate establishedDate) {
    
    
    
    this.establishedDate = establishedDate;
  }


  public SessionBusinessDetailsModel legalName(String legalName) {
    
    
    if (legalName != null && legalName.length() < 3) {
      throw new IllegalArgumentException("Invalid value for legalName. Length must be greater than or equal to 3.");
    }
    
    this.legalName = legalName;
    return this;
  }

   /**
   * Legal name of your business
   * @return legalName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ACME LLC.", value = "Legal name of your business")

  public String getLegalName() {
    return legalName;
  }


  public void setLegalName(String legalName) {
    
    
    if (legalName != null && legalName.length() < 3) {
      throw new IllegalArgumentException("Invalid value for legalName. Length must be greater than or equal to 3.");
    }
    this.legalName = legalName;
  }


  public SessionBusinessDetailsModel dbaName(String dbaName) {
    
    
    if (dbaName != null && dbaName.length() < 3) {
      throw new IllegalArgumentException("Invalid value for dbaName. Length must be greater than or equal to 3.");
    }
    
    this.dbaName = dbaName;
    return this;
  }

   /**
   * The name you are doing business as
   * @return dbaName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ACME", value = "The name you are doing business as")

  public String getDbaName() {
    return dbaName;
  }


  public void setDbaName(String dbaName) {
    
    
    if (dbaName != null && dbaName.length() < 3) {
      throw new IllegalArgumentException("Invalid value for dbaName. Length must be greater than or equal to 3.");
    }
    this.dbaName = dbaName;
  }


  public SessionBusinessDetailsModel taxId(String taxId) {
    
    
    
    
    this.taxId = taxId;
    return this;
  }

   /**
   * Federal Tax Id
   * @return taxId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "123456789", value = "Federal Tax Id")

  public String getTaxId() {
    return taxId;
  }


  public void setTaxId(String taxId) {
    
    
    
    this.taxId = taxId;
  }


  public SessionBusinessDetailsModel website(String website) {
    
    
    
    
    this.website = website;
    return this;
  }

   /**
   * Company website
   * @return website
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "https://www.acme.com", value = "Company website")

  public String getWebsite() {
    return website;
  }


  public void setWebsite(String website) {
    
    
    
    this.website = website;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SessionBusinessDetailsModel instance itself
   */
  public SessionBusinessDetailsModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionBusinessDetailsModel sessionBusinessDetailsModel = (SessionBusinessDetailsModel) o;
    return Objects.equals(this.address, sessionBusinessDetailsModel.address) &&
        Objects.equals(this.phone, sessionBusinessDetailsModel.phone) &&
        Objects.equals(this.establishedDate, sessionBusinessDetailsModel.establishedDate) &&
        Objects.equals(this.legalName, sessionBusinessDetailsModel.legalName) &&
        Objects.equals(this.dbaName, sessionBusinessDetailsModel.dbaName) &&
        Objects.equals(this.taxId, sessionBusinessDetailsModel.taxId) &&
        Objects.equals(this.website, sessionBusinessDetailsModel.website)&&
        Objects.equals(this.additionalProperties, sessionBusinessDetailsModel.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, phone, establishedDate, legalName, dbaName, taxId, website, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionBusinessDetailsModel {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    establishedDate: ").append(toIndentedString(establishedDate)).append("\n");
    sb.append("    legalName: ").append(toIndentedString(legalName)).append("\n");
    sb.append("    dbaName: ").append(toIndentedString(dbaName)).append("\n");
    sb.append("    taxId: ").append(toIndentedString(taxId)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("address");
    openapiFields.add("phone");
    openapiFields.add("establishedDate");
    openapiFields.add("legalName");
    openapiFields.add("dbaName");
    openapiFields.add("taxId");
    openapiFields.add("website");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SessionBusinessDetailsModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SessionBusinessDetailsModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SessionBusinessDetailsModel is not found in the empty JSON string", SessionBusinessDetailsModel.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `address`
      if (jsonObj.get("address") != null && !jsonObj.get("address").isJsonNull()) {
        AddressModel.validateJsonObject(jsonObj.getAsJsonObject("address"));
      }
      if (!jsonObj.get("phone").isJsonNull() && (jsonObj.get("phone") != null && !jsonObj.get("phone").isJsonNull()) && !jsonObj.get("phone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `phone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phone").toString()));
      }
      if (!jsonObj.get("legalName").isJsonNull() && (jsonObj.get("legalName") != null && !jsonObj.get("legalName").isJsonNull()) && !jsonObj.get("legalName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `legalName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("legalName").toString()));
      }
      if (!jsonObj.get("dbaName").isJsonNull() && (jsonObj.get("dbaName") != null && !jsonObj.get("dbaName").isJsonNull()) && !jsonObj.get("dbaName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbaName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbaName").toString()));
      }
      if (!jsonObj.get("taxId").isJsonNull() && (jsonObj.get("taxId") != null && !jsonObj.get("taxId").isJsonNull()) && !jsonObj.get("taxId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `taxId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("taxId").toString()));
      }
      if (!jsonObj.get("website").isJsonNull() && (jsonObj.get("website") != null && !jsonObj.get("website").isJsonNull()) && !jsonObj.get("website").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `website` to be a primitive type in the JSON string but got `%s`", jsonObj.get("website").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SessionBusinessDetailsModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SessionBusinessDetailsModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SessionBusinessDetailsModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SessionBusinessDetailsModel.class));

       return (TypeAdapter<T>) new TypeAdapter<SessionBusinessDetailsModel>() {
           @Override
           public void write(JsonWriter out, SessionBusinessDetailsModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SessionBusinessDetailsModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SessionBusinessDetailsModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SessionBusinessDetailsModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SessionBusinessDetailsModel
  * @throws IOException if the JSON string is invalid with respect to SessionBusinessDetailsModel
  */
  public static SessionBusinessDetailsModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SessionBusinessDetailsModel.class);
  }

 /**
  * Convert an instance of SessionBusinessDetailsModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

