/*
 * Payfactory Api
 * Payfactory specializes in embedded payment facilitation (payfac) services for ISVs and SaaS companies. Our gateway-friendly platform integrates with software systems to provide seamless payment facilitation with little to no development required, allowing our partners to minimize integration costs and quickly gain a new revenue stream. Founded by payment industry veterans, we believe that integrated processing should be simple, frictionless and fast – while also maintaining the highest level of security, customer service and human support.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.DepositModel;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReportingApi
 */
@Disabled
public class ReportingApiTest {

    private static ReportingApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ReportingApi(apiClient);
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAchTransactionsByReferenceIdTest() throws ApiException {
        String referenceId = null;
        List<DepositModel> response = api.getAchTransactionsByReferenceId(referenceId)
                .execute();
        // TODO: test validations
    }

    /**
     * Get current Deposits
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDepositsTest() throws ApiException {
        List<DepositModel> response = api.getDeposits()
                .execute();
        // TODO: test validations
    }

    /**
     * Get {n} current Deposits
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDepositsByCountTest() throws ApiException {
        Integer numberOfDeposits = null;
        List<DepositModel> response = api.getDepositsByCount(numberOfDeposits)
                .execute();
        // TODO: test validations
    }

    /**
     * Get Deposits by ReferenceId.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDepositsByReferenceIdTest() throws ApiException {
        String referenceId = null;
        List<DepositModel> response = api.getDepositsByReferenceId(referenceId)
                .execute();
        // TODO: test validations
    }

}
